PKGNAME=golbd
PKGVERSION=$(shell grep -s 'Version:' golbd.spec |awk '{print $2}' )
PKGRELEASE=$(shell grep -s 'Release:' golbd.spec |awk '{print $2}' )
PKGID=$(PKGNAME)-$(PKGVERSION)
TARFILE=$(PKGID).tgz

all:
	mkdir $(PKGID)
	ls | grep -v -E '$(PKGID)$$|$(PKGNAME)$$|^cluster$|\.git' | xargs cp -rt $(PKGID)
	tar cvzf $(TARFILE) $(PKGID)
	rm -r $(PKGID)

clean:
	rm $(TARFILE)

