PKGNAME=golbd
PKGVERSION=$(shell grep -s 'Version:' golbd.spec |sed 's/Version:\t//' )
PKGRELEASE=$(shell grep -s 'Release:' golbd.spec |sed 's/Release:\t//' )
PKGID=$(PKGNAME)-$(PKGVERSION)
TARFILE=$(PKGID).tgz


all:
	mkdir $(PKGID)
	ls | grep -v -E '$(PKGID)$$|$(PKGNAME)$$|^cluster$|\.git' | xargs cp -rt $(PKGID)
	tar cvzf $(TARFILE) $(PKGID)
	rm -r $(PKGID)

clean:
	rm $(TARFILE)

